#pragma once 


#include <string>


namespace Aliases {
    
    using Price = std::int32_t;
    using Quantity = std::uint32_t;
    using OrderId = std::uint64_t;
    using Symbol = std::string;
    
    enum class Side
    {
        Buy,
        Sell

    };
    enum class OrderType
    {
        FillorKill,
        GoodTillCancel
    };

    struct Order {
        OrderId Id;
        Symbol Ticker;
        Side OrderSide;
        OrderType Type;
        Price OrderPrice;
    public:
        Order(OrderType orderType, OrderId orderId, Side side, Price price, Quantity quantity)
        : m_OrderType {orderType}
        , m_OrderId {orderId}
        , m_side {side}
        , m_price {price}
        , m_InitialQuantity {quantity}
        , m_RemainingQuantity {quantity}

        {}

        OrderId GetOrderId() const {return m_OrderId;}
        Side GetSide() const {return m_side;}
        Price GetPrice() const {return m_price;}
        OrderType GetOrderType() const {return m_OrderType;}
        Quantity GetInitialQuantity() const {return m_InitialQuantity;}
        Quantity GetRemainingQuantity() const {return m_RemainingQuantity;}
        Quantity GetFilledQuantity() const {return GetInitialQuantity() - GetRemainingQuantity() ;}
        bool IsFilled() const {return GetFilledQuantity == 0;}



    private:
        OrderType m_OrderType;
        OrderId m_OrderId;
        Side m_side;
        Price m_price;
        Quantity m_InitialQuantity;
        Quantity m_RemainingQuantity;
        OrderId PlacedTsc;

    };
    

    //generated by Tickers matching engine that gets fullfilled
    struct Trade {
        OrderId BuyOrderId;
        OrderId SellOrderId;
        Price ExecutedPrice;
        Quantity ExecutedQuantity;
        OrderId MatchedTsc;
    };


 
}