#pragma once 


#include <string>


namespace Aliases {
    
    using Price = std::int32_t;
    using Quantity = std::uint32_t;
    using OrderId = std::uint64_t;
    using Symbol = std::string;
    
    enum class Side
    {
        Buy,
        Sell

    };
    enum class OrderType
    {
        FillorKill
    };

    struct Order {
        OrderId Id;
        Symbol Ticker;
        Side OrderSide;
        OrderType Type;
        Price OrderPrice;
        Quantity OrderQuantity;
        OrderId PlacedTsc;

    };
    

    //generated by Tickers matching engine that gets fullfilled
    struct Trade {
        OrderId BuyOrderId;
        OrderId SellOrderId;
        Price ExecutedPrice;
        Quantity ExecutedQuantity;
        OrderId MatchedTsc;
    };


 
}