#pragma once 


#include <string>


namespace Aliases {
    
    using Price = std::int32_t;
    using Quantity = std::uint32_t;
    using OrderId = std::uint64_t;
    using Symbol = std::string;
    enum class Side
    {
        Buy,
        Sell

    };
    enum class OrderType
    {
        FillorKill,
    };

    //Generated by Particpant
    //Passed into MPSC 
    struct Order {
        OrderId Id;
        Symbol Ticker;
        Side OrderSide;
        OrderType Type;
        Price OrderPrice;
        Quantity OrderQuantity;
        uint64_t PlacedTsc;       
    };
    //Generated by Succesful Matching Engine
    struct Trade {
        OrderId BuyOrderId;
        OrderId SellOrderId;
        Price ExecutedPrice;
        Quantity ExecutedQuantity;
        uint64_t MatchedTsc;
    };



}